# Generated by Django 3.2 on 2021-05-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210509_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='trades',
            field=models.ManyToManyField(blank=True, default='', related_name='user_trades_list', to='accounts.Cards'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wants',
            field=models.ManyToManyField(blank=True, default='', related_name='user_wants_list', to='accounts.Cards'),
        ),
    ]
