# Generated by Django 3.2 on 2021-05-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mtgshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mtg_shops',
            field=models.ManyToManyField(blank=True, default='', to='accounts.MtgShop'),
        ),
    ]
