# Generated by Django 3.2 on 2021-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_mtg_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgshop',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
