# Generated by Django 3.2 on 2021-05-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210511_1800'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trades',
            unique_together={('card', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='wants',
            unique_together={('card', 'user')},
        ),
    ]
