from rest_framework import serializers
from .models import *


class RecipeSerializer(serializers.ModelSerializer):
    class Meta:
        model = Recipe
        fields = ("id", "name", "ingredients", "picture", "difficulty", "prep_time", "prep_guide")


# class CardSerializer(serializers.ModelSerializer):
#     class Meta:
#         model = Cards
#         fields = (
#             "id",
#             "artist",
#             "asciiname",
#             "availability",
#             "bordercolor",
#             "cardkingdomfoilid",
#             "cardkingdomid",
#             "coloridentity",
#             "colorindicator",
#             "colors",
#             "convertedmanacost",
#             "dueldeck",
#             "edhrecrank",
#             "faceconvertedmanacost",
#             "facename",
#             "flavorname",
#             "flavortext",
#             "frameeffects",
#             "frameversion",
#             "hand",
#             "hasalternativedecklimit",
#             "hascontentwarning",
#             "hasfoil",
#             "hasnonfoil",
#             "isalternative",
#             "isfullart",
#             "isonlineonly",
#             "isoversized",
#             "ispromo",
#             "isreprint",
#             "isreserved",
#             "isstarter",
#             "isstoryspotlight",
#             "istextless",
#             "istimeshifted",
#             "keywords",
#             "layout",
#             "leadershipskills",
#             "life",
#             "loyalty",
#             "manacost",
#             "mcmid",
#             "mcmmetaid",
#             "mtgarenaid",
#             "mtgjsonv4id",
#             "mtgofoilid",
#             "mtgoid",
#             "multiverseid",
#             "name",
#             "number",
#             "originalreleasedate",
#             "originaltext",
#             "originaltype",
#             "otherfaceids",
#             "power",
#             "printings",
#             "promotypes",
#             "purchaseurls",
#             "rarity",
#             "scryfallid",
#             "scryfallillustrationid",
#             "scryfalloracleid",
#             "setcode",
#             "side",
#             "subtypes",
#             "supertypes",
#             "tcgplayerproductid",
#             "text",
#             "toughness",
#             "type",
#             "types",
#             "uuid",
#             "variations",
#             "watermark",
#         )
